### ISSUE TITLE
address page breaks

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HistoryAmherstCollege#3]
This issue will be closed when page breaks are addressed in the wrangling process. This is needed before #2 since some pages may break with a hyphen!

**Comment by nicholasjhorton** [comment]
This feels like an important next step. Can it happen in parallel with the footnote processing? Let's talk.

**Comment by jpapagelis24** [comment]
We need to figure out what we want to keep when addressing the page breaks. We could perhaps keep the page numbers because they are referenced in other places. Perhaps keep the page number along with the first word or line. Some questions to think of:

- Do we want to keep the page number?
- Where do we store the page number and corresponding line? New table perhaps
- How do we reference back to the chapter? Keep the first 4 words? Need to remember to adjust for hyphens.

**Comment by tknightly24** [comment]
We created a table that extracts the page number, page header (the text next to the page number), and the first line of the page. Our next steps are to remove the extra spaces that make up the page break.

**Comment by nicholasjhorton** [comment]
Thanks for your work on this front. Where can we find the table?

**Comment by tknightly24** [comment]
@nicholasjhorton here is the table we were working on last class: [d6ff211](https://github.com/STAT325-S24/HistoryAmherstCollege/commit/d6ff2116b0632d0ee00abfc2e879d9b3484c41fe)

**Comment by jpapagelis24** [comment]
Created new folders that contain the page tables (`page_tables`) and the depaginated texts for each chapter (`data-raw-depaginate`). This issue is complete unless there are any issues with the tables, text.

**Comment by nicholasjhorton** [comment]
It's *great* to see how this is coming together: nice work!

If the code isn't already being organized in a Quarto file (with associated pdf) can you please move your code into there so that we can track the workflow (I've already fixed some things that will need to be run through one more time).

Same thing will be needed for the code that generates the page subtitles.

**Comment by nicholasjhorton** [comment]
Any updates on this front? It would be great to have a pdf which listed the subtitles as a side effect of processing the workflow for this issue. (This would address open issues #11.)

**Comment by nicholasjhorton** [comment]
And #23!

**Comment by jpapagelis24** [comment]
@nicholasjhorton 

Completed this with commit: df01cc7e289a5a222c31b2fa2f87ea330834f993

See the pdf with the subtitles here: https://github.com/STAT325-S24/HistoryAmherstCollege/blob/main/data-raw/subtitles.pdf

Closing the issue.

**Comment by tknightly24** [comment]
Nick and Justin will work through changing the working directory of the qmd file

**Comment by nicholasjhorton** [comment]
This is looking good but I'm only seeing `subtitles.pdf` not `subtitles.qmd`. Any guidance welcomed.

**Comment by jpapagelis24** [comment]
@nicholasjhorton I did most of the things we talked about in this commit: 79bdf042aa012d18addcd9383cbce23e754d2f83

Some notes:
- the subtitle tables and the processing are now done in 01_processing_pages.qmd
- I meant to delete subtitles.pdf since it is now an earlier version 
-  We still need to add a couple of lines in to process the appendix

**Comment by nicholasjhorton** [comment]
Thanks for your work on this front.

Is the appendix change needed (since I renamed it to `chapter29.txt`)?

**Comment by nicholasjhorton** [comment]
@jpapagelis24 @tknightly24 might you be willing to update this issue with the current status of this work? Thanks in advance, Nick

**Comment by jpapagelis24** [comment]
@nicholasjhorton This is complete. Closing the issue.
